services:
  postgres:
    image: postgres:17-alpine
    container_name: pgsql7
    env_file:
      - env/postgres.env
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'

  nginx:
    image: nginx:1-alpine
    container_name: nginx
    ports:
      - '80:80'

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - env/api.env
    ports:
      - '3001:3001'
    depends_on:
      - postgres

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    container_name: analyzer
    env_file:
      - env/analyzer.env
    ports:
      - '3002:3002'
    depends_on:
      - prometheus
      - loki